catalogMode: prefer
cleanupUnusedCatalogs: true

publicHoistPattern:
  - "@typescript/*"
  - vite

shellEmulator: true

packages:
  - src

patchedDependencies:
  "@rbxts/jest-globals": patches/@rbxts__jest-globals.patch
  roblox-ts: patches/roblox-ts.patch

catalogs:
  build:
    tsdown: ^0.20.3
    unplugin-unused: ^0.5.7
  cli:
    bumpp: ^10.4.1
    pncat: ^0.9.1
  dev:
    "@antfu/ni": ^28.2.0
    file-entry-cache: ^11.1.2
    madge: ^8.0.0
  integration:
    "@rbxts/compiler-types": 3.0.0-types.0
    roblox-ts: ^3.0.0
  lint:
    "@isentinel/eslint-config": ^4.8.2
    "@vitest/eslint-plugin": ^1.6.7
    eslint: ^9.39.2
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-n: ^17.23.2
    eslint-plugin-pnpm: ^1.5.0
    eslint_d: ^14.3.0
    lint-staged: ^16.2.7
    publint: ^0.3.17
    simple-git-hooks: ^2.13.1
  peer:
    "@roblox-ts/path-translator": ^1.1.0
    "@roblox-ts/rojo-resolver": ^1.1.0
  script:
    jiti: ^2.6.1
  test:
    "@rbxts/jest": 3.13.3-ts.1
    "@rbxts/jest-globals": 3.13.3-ts.1
    "@vitest/coverage-v8": ^4.0.18
    vitest: ^4.0.18
  tsc:
    "@isentinel/tsconfig": ^1.2.0
    "@typescript/native-preview": 7.0.0-dev.20260212.1
    better-typescript-lib: ^2.12.0
    get-tsconfig: ^4.13.6
    typescript: ~5.8.2
  types:
    "@rbxts/types": ^1.0.907
    "@types/node": ^24.10.13
    type-fest: ^5.4.4

onlyBuiltDependencies:
  - simple-git-hooks
